AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
      VersioningConfiguration:
        Status: Enabled

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      LifecycleConfiguration:
        Rules:
          # incoming/ → 24 hours
          - Id: IncomingTTL
            Status: Enabled
            Prefix: incoming/
            ExpirationInDays: 1

          # processing/ → 24 hours
          - Id: ProcessingTTL
            Status: Enabled
            Prefix: processing/
            ExpirationInDays: 1

          # error/ → 7 days
          - Id: ErrorTTL
            Status: Enabled
            Prefix: error/
            ExpirationInDays: 7

          # processed/ → 30 days
          - Id: ProcessedTTL
            Status: Enabled
            Prefix: processed/
            ExpirationInDays: 30

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: The created S3 bucket name