name: Build Firmware FFC0806-2305

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1.1.2
        with:
          cli-version: 0.35.3
          #fqbn: "esp32:esp32:firefly_controller"
          fqbn: "esp32:esp32:esp32wrover"
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              version: 2.0.11
          libraries: |
            - source-url: https://github.com/adafruit/Adafruit_BusIO.git
              version: 1.14.1
            - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
              version: 1.11.5
            - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
              version: 2.5.7
            - source-url: https://github.com/bblanchon/ArduinoJson.git
              version: v6.21.5
            - source-url: https://github.com/bblanchon/ArduinoStreamUtils.git
              version: v1.9.0
            - source-url: https://github.com/BrentIO/AsyncTCP.git
              version: 2024.2.1
            - source-url: https://github.com/BrentIO/AsyncWebServer_ESP32_W5500.git
              version: 2024.7.1
            - source-url: https://github.com/BrentIO/ESPAsyncWebServer.git
              version: 2024.7.1
            - source-url: https://github.com/BrentIO/esp32FOTA.git
              version: 2024.8.2
            - source-url: https://github.com/BrentIO/PCA95x5.git
              version: 2023.10.2
            - source-url: https://github.com/BrentIO/PCT2075.git
              version: 2023.10.3
            - source-url: https://github.com/BrentIO/pubsubclient.git
              version: 2025.4.1
            - source-url: https://github.com/arduino-libraries/Ethernet.git
              version: 2.0.2
            - source-url: https://github.com/RobTillaart/I2C_EEPROM.git
              version: 1.7.1
            - source-url: https://github.com/ivanseidel/LinkedList.git
              version: v1.3.3
            - source-url: https://github.com/arduino-libraries/NTPClient.git
              version: 3.2.1
            - source-url: https://github.com/RobTillaart/PCA9685_RT.git
              version: 0.4.1
            - source-url: https://github.com/nickgammon/Regexp.git
              version: 0.1.1
          cli-compile-flags: |
            - --build-property
            - "build.extra_flags=-DASYNCWEBSERVER_REGEX -DPRODUCT_HEX=0x08062305 -DESP32"
          sketch-paths: |
            - Controller
